{% set version = "4.9" %}

package:
  name: cgal
  version: {{ version }}

source:
  fn: CGAL-{{ version }}.zip
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.zip
  sha256: 34669adf0378e30555df28cc4eef3ef7f46f35c984f4c99a3a16417035dfe083

build:
  number: 4
  features:
    - vc14  # [win and py>=35]
  # mpfr only supports vc14
  skip: true  # [win and py<35]

requirements:
  build:
    - toolchain
    - python
    - cmake
    - boost-cpp 1.63.*
    - mpfr 3.*
    - eigen
    - swig
  run:
    - python
    - boost-cpp 1.63.*
    - mpfr 3.*

test:
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL.so  # [linux]
    - test -f ${PREFIX}/lib/libCGAL.dylib  # [osx]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]
  imports:
    - CGAL

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - xantares
