{% set version = "4.14.1" %}

package:
  name: cgal
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.tar.xz
  sha256: d4ec2528b88a7c3a07b0b86db96c216822f85b951bf4bc7f9d1f26bf6c369afe

build:
  number: 0
  skip: true  # [(win and py<35)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - eigen
    - ninja  # [win]
    - swig
  host:
    - cgal-cpp {{ version }}
    - python
  run:
    - cgal-cpp {{ version }}
    - python

test:
  imports:
    - CGAL
    - CGAL.CGAL_Kernel
    - CGAL.CGAL_Triangulation_2
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  license_file: LICENSE.txt
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
