{% set version = "4.12" %}

package:
  name: cgal
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.zip
  sha256: a1fb463b76d5f5ff7677127708fa98d6ab4f31c22b7ef2cf1ce88419af809dc2

build:
  number: 2
  # mpfr only supports vc14
  skip: true  # [win and py<35]

requirements:
  build:
    - swig
    - cmake
    - eigen
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost-cpp
    - mpfr
  run:
    - python
    - boost-cpp
    - mpfr

test:
  imports:
    - CGAL
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]
    - ! test -f ${PREFIX}/lib/cmake/CGAL/FindGLEW.cmake  # [not win]
    - test -f ${PREFIX}/lib/CGAL/cmake-extra/FindGLEW.cmake  # [not win]
    - if exist %LIBRARY_LIB%\cmake\CGAL\FindGLEW.cmake exit 1  # [win]
    - if not exist %LIBRARY_LIB%\CGAL\cmake-extra\FindGLEW.cmake exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
