{% set version = "5.5.1" %}

package:
  name: cgal
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal-swig-bindings/archive/refs/tags/v5.5.1.post202210141207.zip
  sha256: ff06410df2b47baf737ed1641a6c347ed19478b6653ed0ae1e53a6c76b4bb189
  patches:
    - osx-fix.patch  # [osx]

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - eigen
    - make  # [unix]
    - ninja  # [win]
    - swig
  host:
    - cgal-cpp {{ version }}
    - numpy
    - python
  run:
    - cgal-cpp {{ version }}
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - CGAL
    - CGAL.CGAL_Kernel
    - CGAL.CGAL_Triangulation_2
    - CGAL.CGAL_AABB_tree
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]

about:
  home: http://www.cgal.org/
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.GPL
    - LICENSE.COMMERCIAL
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
    - lrineau
    - maxGimeno
