{% set version = "4.11" %}

package:
  name: cgal
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.zip
  sha256: e74cb61b780f2fd04924761b6f7fd90c73df9997a670fab730c82236f00f1984

build:
  number: 1
  features:
    - vc14  # [win and (py35 or py36)]
  # mpfr only supports vc14
  skip: true  # [win and py<35]

requirements:
  build:
    - toolchain
    - python
    - cmake
    - boost-cpp 1.66.*
    - mpfr 3.1.*
    - eigen
    - swig

  run:
    - python
    - boost-cpp 1.66.*
    - mpfr 3.1.*

test:
  imports:
    - CGAL
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - xantares
