{% set version = "4.10.1" %}

package:
  name: cgal
  version: {{ version }}

source:
  fn: CGAL-{{ version }}.zip
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.zip
  sha256: 27006501ab2ebd5a07849dbfb34ae2331d5afcf316d6e5484b4e10a89ea53dd6

build:
  number: 0
  features:
    - vc14  # [win and py>=35]
  # mpfr only supports vc14
  skip: true  # [win and py<35]

requirements:
  build:
    - toolchain
    - python
    - cmake
    - boost-cpp 1.64.*
    - mpfr 3.*
    - eigen
    - swig
  run:
    - python
    - boost-cpp 1.64.*
    - mpfr 3.*

test:
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]
  imports:
    - CGAL

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - xantares
