{% set version = "5.6.post202310050933" %}
# If `version` is changed but the base version is not, the build number must be incremented.
# Reset the build number to 0 if the base version is changed, for example from 5.6 to 6.0.
{% set base_verson = ".".join(version.split(".")[:-1]) if version.split(".")[-1].startswith("post") else version %}

package:
  name: cgal
  version: {{ base_verson }}

source:
  url: https://github.com/CGAL/cgal-swig-bindings/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bc7380405a5a083030dc90a33cda31077b0b7f4b470d7ce292474ab3c87246a3

build:
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - eigen
    - make  # [unix]
    - ninja  # [win]
    # https://github.com/conda-forge/cgal-feedstock/pull/75#issuecomment-1305660884
    - swig <4.1
  host:
    - cgal-cpp {{ base_verson }}
    - libboost-devel
    - numpy
    - python
  run:
    - cgal-cpp {{ base_verson }}
    - mpfr
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - CGAL
    - CGAL.CGAL_Kernel
    - CGAL.CGAL_Triangulation_2
    - CGAL.CGAL_AABB_tree
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]

about:
  home: http://www.cgal.org/
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.GPL
    - LICENSE.COMMERCIAL
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
    - lrineau
    - maxGimeno
