{% set version = "4.14" %}

package:
  name: cgal
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal-swig-bindings/archive/55635605ed9287f963800d2e0dc5dac6bd3fa899.zip
  sha256: efa305ae2f9c58fd8009f438900925cbf000d8f6789dd08551423640e06ab50a

build:
  number: 1
  skip: true  # [(win and py<35)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - eigen
    - ninja  # [win]
    - swig
  host:
    - cgal-cpp {{ version }}
    - numpy
    - python
  run:
    - cgal-cpp {{ version }}
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - CGAL
    - CGAL.CGAL_Kernel
    - CGAL.CGAL_Triangulation_2
    - CGAL.CGAL_AABB_tree
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]
    - conda inspect linkages $PKG_NAME  # [not win]
    - conda inspect objects $PKG_NAME  # [osx]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
