{% set version = "4.8.1" %}

package:
  name: cgal
  version: {{ version }}

source:
  fn: CGAL-{{ version }}.zip
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.zip
  md5: 2780a9c046cbbf26838b8275d2719d5c
  patches:
    - cgal-mpir.patch  # [win]

build:
  number: 1
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
  skip: true  # [win64 or (win and (not py35))]

requirements:
  build:
    - toolchain
    - python
    - cmake
    - boost 1.61.*
    - mpfr
    - zlib 1.2.*
    - eigen
    - swig
    - numpy
  run:
    - python
    - boost 1.61.*
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL.so  # [linux]
    - test -f ${PREFIX}/lib/libCGAL.dylib  # [osx]
  imports:
    - CGAL

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - xantares

