# If `version` is changed but the base version is not, the build number must be incremented.
# Reset the build number to 0 if the base version is changed, for example from 5.6 to 6.0.
schema_version: 1

context:
  version: 6.0.1.post202410241521
  base_version: ${{ (version | split(".") | list)[:-1] | join(".") if (version | split(".") | list | length) > 3 else version }}

package:
  name: cgal
  version: ${{ base_version }}

source:
  url: https://github.com/CGAL/cgal-swig-bindings/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e9847d302d72a6e8735c7cf083f3ed02d3a4dc5389bbee628fbded768ff522d8

build:
  number: 4

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    # https://github.com/conda-forge/cgal-feedstock/pull/75#issuecomment-1305660884
    - swig <4.1
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - numpy
        - python
    - if: unix
      then: make
    - if: win
      then: ninja
  host:
    - cgal-cpp ${{ base_version }}.*
    - libboost-devel
    - eigen
    - gmp
    - mpfr
    - numpy
    - python
  run:
    - cgal-cpp ${{ base_version }}.*
    - python

tests:
  - python:
      imports:
        - CGAL
        - CGAL.CGAL_Kernel
        - CGAL.CGAL_Triangulation_2
        - CGAL.CGAL_AABB_tree
      pip_check: false
  - script:
      - if: unix
        then: test -f ${PREFIX}/include/CGAL/AABB_tree.h
      - if: win
        then: if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.GPL
    - LICENSE.COMMERCIAL
  summary: Computational Geometry Algorithms Library
  homepage: http://www.cgal.org/

extra:
  recipe-maintainers:
    - tadeu
    - lrineau
    - maxGimeno
